const { test, expect } = require('@playwright/test');

test('desktop: modes, stream, rendering, copy, rename and refresh', async ({ page, context }, testInfo) => {
    await context.grantPermissions(['clipboard-read', 'clipboard-write']);
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/');
    await expect(page.locator('.sidebar-right')).toBeVisible();
    await expect(page.locator('#notice')).toBeHidden();
    await page.screenshot({ path: testInfo.outputPath('desktop-home.png'), fullPage: true });
    await page.locator('#newMode').selectOption('paper');
    await page.locator('#btnNewSession').click();
    await expect(page.locator('#modeBadge')).toHaveText('论文阅读');
    await page.locator('#newMode').selectOption('review');
    await page.locator('#btnNewSession').click();
    await expect(page.locator('#modeBadge')).toHaveText('复习教练');
    await page.locator('#newMode').selectOption('code');
    await page.locator('#btnNewSession').click();
    await page.locator('#chatInput').fill('讲解函数，并测试注入');
    await page.locator('#btnSend').click();
    await expect(page.locator('.message-row.user')).toHaveCount(1);
    await expect(page.locator('#btnSend')).toBeDisabled();
    await expect(page.locator('.message-status')).toHaveCount(0);
    await expect(page.locator('pre code')).toContainText('def greet');
    await expect(page.locator('pre code.hljs')).toHaveCount(1);
    await expect(page.locator('.message-bubble script, .message-bubble img')).toHaveCount(0);
    expect(await page.evaluate(() => window.injected)).toBeUndefined();
    await expect(page.locator('.message-bubble a[href^="javascript:"]')).toHaveCount(0);
    await page.locator('.copy-code').click();
    await expect(page.locator('.copy-code')).toHaveText('已复制');
    expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('def greet');
    await page.locator('#btnRename').click();
    await page.locator('#renameInput').fill('函数基础笔记');
    await page.locator('#renameForm button[type=submit]').click();
    await expect(page.locator('#sessionName')).toHaveText('函数基础笔记');
    await page.screenshot({ path: testInfo.outputPath('desktop-answer.png'), fullPage: true });
    await page.reload();
    await page.getByRole('button', { name: /函数基础笔记/ }).click();
    await expect(page.locator('.message-row')).toHaveCount(2);
    await expect(page.locator('#modeBadge')).toHaveText('代码导师');
    await expect(page.locator('.empty-state')).toHaveCount(0);
    expect(errors).toEqual([]);
});

test('switching sessions cannot receive another session answer; repeated Enter blocked', async ({ page }) => {
    await page.goto('/');
    await page.locator('#btnNewSession').click();
    await page.locator('#chatInput').fill('并发测试');
    let requests = 0;
    page.on('request', request => { if (request.url().endsWith('/messages/stream')) requests++; });
    await page.locator('#chatInput').press('Enter');
    await page.locator('#chatInput').dispatchEvent('keydown', { key: 'Enter' });
    await page.getByRole('button', { name: /历史字谜会话/ }).click();
    await expect(page.locator('#chatInput')).toBeDisabled();
    await expect(page.locator('.message-row.assistant')).toContainText('历史字谜记录');
    await expect(page.locator('#btnNewSession')).toBeEnabled();
    await expect(page.locator('.message-row')).toHaveCount(1);
    expect(requests).toBe(1);
    await page.getByRole('button', { name: /并发测试/ }).click();
    await expect(page.locator('pre code')).toContainText('def greet');
    await expect(page.locator('#btnRename')).toBeEnabled();
});

test('failed stream keeps draft and partial answer; retry saves exactly one turn', async ({ page }) => {
    await page.goto('/');
    await page.locator('#btnNewSession').click();
    await page.locator('#chatInput').fill('模拟失败');
    await page.locator('#btnSend').click();
    await expect(page.locator('.message-status.failed')).toContainText('未完成');
    await expect(page.locator('#chatInput')).toHaveValue('模拟失败');
    await page.locator('#chatInput').fill('现在重试');
    await page.locator('#btnSend').click();
    await expect(page.locator('#sessionName')).toHaveText('现在重试');
    await expect(page.locator('.message-row')).toHaveCount(2);
    await expect(page.locator('.message-status.failed')).toHaveCount(0);
    await page.reload();
    await page.getByRole('button', { name: /现在重试/ }).click();
    await expect(page.locator('.message-row')).toHaveCount(2);
});

test('a delayed history snapshot cannot overwrite a newly completed answer', async ({ page }) => {
    await page.goto('/');
    await page.locator('#btnNewSession').click();
    const id = await page.locator('.record-item.active').getAttribute('data-id');
    let release;
    const gate = new Promise(resolve => { release = resolve; });
    let captured = false;
    await page.route('**/api/sessions/' + id, async route => {
        const response = await route.fetch();
        captured = true;
        await gate;
        await route.fulfill({ response });
    });
    await page.locator('#chatInput').fill('延迟快照测试');
    await page.locator('#btnSend').click();
    await page.getByRole('button', { name: /历史字谜会话/ }).click();
    await page.locator('.record-item[data-id="' + id + '"]').click();
    await expect.poll(() => captured).toBe(true);
    await expect(page.locator('#sessionName')).toHaveText('延迟快照测试');
    release();
    await expect(page.locator('#chatInput')).toBeEnabled();
    await expect(page.locator('.message-row')).toHaveCount(2);
    await expect(page.locator('pre code')).toContainText('def greet');
});

test('mobile: navigation, IME, multiline input and deletion', async ({ page }, testInfo) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto('/');
    await expect(page.locator('.sidebar-right')).toBeHidden();
    await expect(page.locator('#sessionSidebar')).toBeHidden();
    await page.locator('#btnMenu').click();
    await page.locator('#newMode').selectOption('code');
    await page.locator('#btnNewSession').click();
    await expect(page.locator('#sessionSidebar')).toBeHidden();
    const input = page.locator('#chatInput');
    await input.fill('输入法测试');
    await input.dispatchEvent('keydown', { key: 'Enter', isComposing: true });
    await expect(page.locator('.message-row.user')).toHaveCount(0);
    await input.press('End');
    await input.press('Shift+Enter');
    await expect(input).toHaveValue('输入法测试\n');
    await input.fill('移动端练习');
    await input.press('Enter');
    await expect(page.locator('#sessionName')).toHaveText('移动端练习');
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath('mobile-answer.png'), fullPage: true });
    await page.locator('#btnDelete').click();
    await page.locator('#deleteForm button[type=submit]').click();
    await expect(page.locator('#deleteDialog')).not.toBeVisible();
    await page.locator('#btnMenu').click();
    await expect(page.getByRole('button', { name: /移动端练习/ })).toHaveCount(0);
});
